apiVersion: v1
kind: Secret
metadata:
  name: {{ include "investment-crew.fullname" . }}-secrets
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  serper-api-key: {{ .Values.secrets.serperApiKey | b64enc | quote }}
